### ISSUE TITLE
Integration Question

### ISSUE THREAD

**Issue by shadowdraon319** [DrMoriarty/godot-appsflyer#2]
Does this implementation of the SDK automatically track app install conversion events for use with Google Ads and Facebook Ads?

**Comment by DrMoriarty** [comment]
Yes. Installation tracking and attribution processed automatically.

**Comment by shadowdraon319** [comment]
I tried implementing, however, when I try to do the App Flyer SDK install test from their website, it is unable to track the install. My app key and dev key are correct and I registered my test device and it has a proper IDFA. Could this be because the SDK isn't updated to the latest version? In xCode, I see the following messages:

AppsFlyer plugin inited with key and app id
AppsFlyer SDK version 5.2.0 started build (964)

**Comment by DrMoriarty** [comment]
Do you use iOS or Android SDK integration?

**Comment by DrMoriarty** [comment]
@shadowdraon319 I updated plugin to use SDK 6.1. Check it please.

**Comment by shadowdraon319** [comment]
Thank you so much for updating it! However, it still isn't working for me. Is there any way to turn on the SDK's debug mode. https://support.appsflyer.com/hc/en-us/articles/360001559405-Test-mobile-SDK-integration-with-the-app#debugging-debugging-for-ios

**Comment by DrMoriarty** [comment]
@shadowdraon319 updated plugin: added debug log for iOS, also added Apple AppID to plugin settings.

**Comment by shadowdraon319** [comment]
I'm confused, did you commit it? How do I turn on the debug log? Sorry for so many questions, I need to integrate this so I can  promote my game with Google Ads. I appreciate your help.

**Comment by DrMoriarty** [comment]
Yes, I forgot to commit it to github, but I did't forget to upload compiled plugin to the repository. You should press button "REPO" in right bottom corner of NativeLib view. Then it fetch all actual plugin info from the repository. Then you can press "Update" button on AppsFlyer plugin (or Install if you uninstalled it first).
The gd wrapper check if OS.is_debug_build() and enable debug output in this case. So you will see more internal log when you start your app.

**Comment by Octowyth** [comment]
hi @DrMoriarty 

Thank you so much for creating this plugin, I have some question about the android integration :
I'm using Godot 3.2.3, I've install NativeLib and install Appsflyer Plugin from UI and input my DevKey
![image](https://user-images.githubusercontent.com/80591569/111038384-26a26780-845b-11eb-8d5d-5c6e8d29dc0a.png)

I call this in my gd script after I finish the level in my game
var dict = {"level": "10"}
appsflyer.event("Level 10",dict)

but when I test non organic install and in app event test using my appsflyer testing device I got nothing,
any advice on how to test the android integration ?

I've also put this codes in my androidManifest.xml :
`<receiver android:name="com.appsflyer.SingleInstallBroadcastReceiver" android:exported="true">
		<intent-filter>
			 <action android:name="com.android.vending.INSTALL_REFERRER" />
		 </intent-filter>
	</receiver>	`
Thanks

**Comment by DrMoriarty** [comment]
Hi @Octowyth 
I'm not sure that adding SingleInstallBroadcastReceiver is actually needed in your case. In the plugin already exist MultipleInstallBroadcaseReceiver which is better in many cases.
For testing AppsFlyer integration you should refer to the official documentation.
Also see you application logs. The plugin enables debug output for AppsFlyer SDK on debug builds.

**Comment by Octowyth** [comment]
Hi @DrMoriarty 

I've follow the readme and check the debug log and found this error when installing my game to android device, 
![image](https://user-images.githubusercontent.com/80591569/111488269-ac7c2680-876b-11eb-8c22-4f9a9c56155d.png)

I've install the appsflyer module and also add the appsflyer.gd in autoload list

![image](https://user-images.githubusercontent.com/80591569/111488228-a25a2800-876b-11eb-8101-25981092effc.png)

please advice if there's anything I need to do ?

thanks

**Comment by DrMoriarty** [comment]
@Octowyth 
As far as I see on your previous screenshot, you didn't enabled any platforms.
In NativeLib window at the top there are two checkboxes for Android and iOS. You should enable at least one of them and then reinstall plugin.

**Comment by Octowyth** [comment]
Hi @DrMoriarty 

all good now :D 
thank you so much

**Comment by Octowyth** [comment]
sorry to bother again @DrMoriarty 
may I know what this permission used for ?
<uses-permission android:name="android.permission.READ_PHONE_STATE" />

is there any issue if I remove this ?
I'm asking because my game got error when trying to upload to google play store
and need to provide web hosted privacy policy for that permission

thanks

**Comment by DrMoriarty** [comment]
I checked https://support.appsflyer.com/hc/en-us/articles/207032126-Android-SDK-integration-for-developers#integration-23-set-required-permissions
and noticed that it requires now only INTERNET, ACCESS_NETWORK_STATE and ACCESS_WIFI_STATE. As far as I remember the old version of AppsFlyer SDK required READ_PHONE_STATE but it is not necessary now.
I rebuild android plugin and published it as 0.2.3 (without READ_PHONE_STATE)

**Comment by slabgames** [comment]
I have this problem too on Godot 3.3.2 with godot-appsflyer version 0.3.2. Installed everything correctly, and checked Appsflyer on Export Project settings.
When I tested using SDK Integration Test Tool on Appsflyer, it doesn't track the install

**Comment by slabgames** [comment]
Does it probably need a new version of SDK? It's now on 6.3.2

**Comment by DrMoriarty** [comment]
yes, it may be outdated sdk issue.
I will update it soon

**Comment by slabgames** [comment]
Quoted this from the documentation :
```
You can defer the SDK initialization by calling start from an Activity class, instead of calling it in the Application class. init should still be called in the Application class.

Typical usage of deferred SDK start is when an app would like to request consent from the user to collect data in the Main Activity, and call start after getting the user's consent.
```
Could it be the source of problem? init should be called from Application onCreate 
https://imgur.com/a/7Y7gODN

**Comment by hoalx97** [comment]
hi every one.
I'm trying to install AppsFlyer to my app, but when I try to install it into a real device and i get this error.

![image](https://user-images.githubusercontent.com/79313655/149123419-8c6a23b1-7e7a-4f32-a1cb-7e1d4ef607b4.png)


please advice if there's anything I need to do ?

thanks
